package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"
	"gql_jobportal/graph/model"
)

// CreateUser is the resolver for the CreateUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	return r.Service.CreateUser(input)
}

// CreateCompany is the resolver for the CreateCompany field.
func (r *mutationResolver) CreateCompany(ctx context.Context, input model.NewCompany) (*model.Company, error) {
	return r.Service.CreateCompany(input)
}

// CreateJob is the resolver for the CreateJob field.
func (r *mutationResolver) CreateJob(ctx context.Context, input model.NewJob) (*model.Job, error) {
	return r.Service.CreateJob(input)
}

// ViewAllCompany is the resolver for the ViewAllCompany field.
func (r *queryResolver) ViewAllCompany(ctx context.Context) ([]*model.Company, error) {
	return r.Service.ViewAllCompanies()
}

// ViewCompanyByID is the resolver for the ViewCompanyById field.
func (r *queryResolver) ViewCompanyByID(ctx context.Context, companyID string) (*model.Company, error) {
	return r.Service.ViewCompanyByID(companyID)
}

// ViewByJobID is the resolver for the ViewByJobID field.
func (r *queryResolver) ViewByJobID(ctx context.Context, id string) (*model.Job, error) {
	return r.Service.ViewJobByID(id)
}

// ViewJobByCompanyID is the resolver for the ViewJobByCompanyID field.
func (r *queryResolver) ViewJobByCompanyID(ctx context.Context, companyID string) ([]*model.Job, error) {
	return r.Service.ViewJobByCompanyID(companyID)
}

// ViewAllJob is the resolver for the viewAllJob field.
func (r *queryResolver) ViewAllJob(ctx context.Context) ([]*model.Job, error) {
	return r.Service.ViewAllJob()
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *mutationResolver) UserSignup(ctx context.Context, input model.NewUser) (*model.User, error) {
	return r.Service.CreateUser(input)
}
func (r *queryResolver) ViewJobByID(ctx context.Context, id string) (*model.Job, error) {
	panic(fmt.Errorf("not implemented: ViewJobByID - ViewJobById"))
}
func (r *queryResolver) ViewJobByCid(ctx context.Context, cid string) ([]*model.Job, error) {
	panic(fmt.Errorf("not implemented: ViewJobByCid - ViewJobByCid"))
}
